version: '3.7'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: "tayle_backend"
    container_name: tayle_app
    environment:
      - TZ=Asia/Yekaterinburg
    restart: always
    command: gunicorn tayle.wsgi:application --bind 0.0.0.0:5445
    volumes:
      - tmp_files:/tmp_files
      - ./logs:/logs
      - ./backend:/code
      - ./settings.py:/code/tayle/settings.py
    env_file:
      - ./.env
    network_mode: host
    ports:
      - 5445

volumes:
  tmp_files:

