# Generated by Django 2.2.8 on 2021-09-18 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountList',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('blocked', 'Blocked'), ('closed', 'Closed')], default='active', max_length=7)),
                ('currency', models.CharField(choices=[('rub', 'Rouble')], default='rub', max_length=3)),
                ('sum', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'account_list',
            },
        ),
    ]
