# Generated by Django 2.2.8 on 2021-09-18 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountlist',
            options={'verbose_name': 'Счет', 'verbose_name_plural': 'Счета'},
        ),
        migrations.CreateModel(
            name='AccountMovements',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('sum', models.FloatField()),
                ('time_created', models.TimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipient', to='accounts.AccountList')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sender', to='accounts.AccountList')),
            ],
            options={
                'verbose_name': 'Движение по счету',
                'verbose_name_plural': 'Движение по счетам',
                'db_table': 'account_movements',
            },
        ),
    ]
