# Generated by Django 2.2.8 on 2021-09-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210918_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountlist',
            name='currency',
            field=models.CharField(choices=[('rub', 'Рубли')], default='rub', max_length=3),
        ),
        migrations.AlterField(
            model_name='accountlist',
            name='status',
            field=models.CharField(choices=[('active', 'Активный'), ('blocked', 'Заблокированный'), ('closed', 'Закрытый')], default='active', max_length=7),
        ),
    ]
