# Generated by Django 2.2.8 on 2021-09-19 06:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210918_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountlist',
            name='sum',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
