# Generated by Django 2.2.8 on 2021-09-19 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210919_0610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountlist',
            old_name='sum',
            new_name='balance',
        ),
    ]
