# Generated by Django 2.2.8 on 2021-09-19 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210919_0614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountmovements',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='accountmovements',
            name='sender',
        ),
        migrations.AddField(
            model_name='accountmovements',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='account', to='accounts.AccountList'),
        ),
        migrations.AddField(
            model_name='accountmovements',
            name='related_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='related_account', to='accounts.AccountList'),
        ),
        migrations.AddField(
            model_name='accountmovements',
            name='type',
            field=models.CharField(choices=[('debited', 'Списаны'), ('credited', 'Зачислены')], default='credited', max_length=8),
        ),
    ]
