# Generated by Django 2.2.8 on 2021-09-19 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210919_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmovements',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
